"""Execution-resource analysis over canonical SSA opcodes."""
from .context import (
    APP_CALL_OPCODE_BUDGET,
    LOGICSIG_MAX_COST,
    MAX_GROUP_APP_CALLS,
    MAX_GROUP_LOGICSIGS,
    MAX_INNER_APP_CALLS,
    MAX_POOLED_LOGICSIG_COST,
    MAX_POOLED_OPCODE_BUDGET,
    MAX_STACK_DEPTH,
    BudgetContext,
    ProgramMode,
    infer_avm_version,
    infer_program_mode,
)
from .costs import (
    CostFact,
    assignment_cost,
    block_cost,
    block_stack_delta,
    canonical_assignments,
    op_cost,
)
from .loop_bounds import LoopBound, analyze_loops, draw, render, to_dot
from .queries import MinimumCost, minimum_cost, minimum_costs
from .advanced import (
    BudgetExhaustionCandidate,
    MethodBudgetSummary,
    OpcodeBudgetGuard,
    analyze_opcode_budget_guards,
    find_budget_exhaustion_candidates,
    summarize_methods,
)

__all__ = [
    "APP_CALL_OPCODE_BUDGET",
    "LOGICSIG_MAX_COST",
    "MAX_GROUP_APP_CALLS",
    "MAX_GROUP_LOGICSIGS",
    "MAX_INNER_APP_CALLS",
    "MAX_POOLED_LOGICSIG_COST",
    "MAX_POOLED_OPCODE_BUDGET",
    "MAX_STACK_DEPTH",
    "BudgetContext",
    "ProgramMode",
    "infer_avm_version",
    "infer_program_mode",
    "CostFact",
    "assignment_cost",
    "block_cost",
    "block_stack_delta",
    "canonical_assignments",
    "op_cost",
    "LoopBound",
    "analyze_loops",
    "draw",
    "render",
    "to_dot",
    "MinimumCost",
    "minimum_cost",
    "minimum_costs",
    "BudgetExhaustionCandidate",
    "MethodBudgetSummary",
    "OpcodeBudgetGuard",
    "analyze_opcode_budget_guards",
    "find_budget_exhaustion_candidates",
    "summarize_methods",
]
