"""Algoplonk verifier rekey-bug demo.

Generates two reports under this directory:

  - ``vuln_rekey_report.txt``   (1 violation expected — pre-fix logicsig)
  - ``fixed_rekey_report.txt``  (0 violations — post-fix logicsig adds
                                 ``assert py.Txn.rekey_to == py.Global.zero_address``)

Source: the BLS12_381 Basic verifier logicsig from
https://github.com/giuliop/AlgoPlonk, generated by compiling the
Pythagorean ``a*a + b*b == c*c`` circuit at the commit before and at
the commit that adds the rekey guard (``1939a589``,
"fix verifier logicsig rekey guard").

CLI:

    # From the repo root (works installed or not — the script adds the
    # source roots to sys.path itself):
    python examples/algoplonk/run_rekey_demo.py

Paths resolve relative to this script's location, so the CWD doesn't
matter.
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(REPO / "src"))            # -> the tealql package

from tealql.tealtools.ssa import SSAProgram, PySSA
from tealql.tealtools.passes.orchestrate import run_all_passes
from tealql.security import RekeyToDetector


def run_one(kind: str) -> int:
    db_path = HERE / kind / "db"
    print(f"\n=== {kind.upper()} ({db_path.relative_to(REPO)}) ===", flush=True)
    prog_ql = SSAProgram(str(db_path), verbose=False)
    prog = PySSA.build(prog_ql)
    run_all_passes(prog)
    viols = RekeyToDetector(prog).detect()
    print(f"  rekey-to violations: {len(viols)}")
    for v in viols:
        print(f"    {v}")
    rpt = HERE / f"{kind}_rekey_report.txt"
    with rpt.open("w") as f:
        f.write(f"# RekeyToDetector report — {kind} (DB: {db_path.relative_to(REPO)})\n")
        f.write(f"# Violations: {len(viols)}\n\n")
        if not viols:
            f.write("(no rekey-to violations detected)\n")
        else:
            for i, v in enumerate(viols, 1):
                f.write(f"--- violation {i} ---\n{v}\n\n")
    print(f"  wrote: {rpt.relative_to(REPO)}")
    return len(viols)


def main() -> int:
    n_vuln = run_one("vuln")
    n_fixed = run_one("fixed")
    print()
    print(f"summary: vuln={n_vuln}  fixed={n_fixed}  "
          f"({'OK' if n_vuln > 0 and n_fixed == 0 else 'UNEXPECTED'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
