"""Module-to-visualization coverage decisions.

This is the maintenance tripwire behind "every representation, analysis, and
pass".  Every product-bearing tealtools module names at least one catalog view;
support-only modules are explicitly classified with a reason.  The test suite
discovers files from disk, so adding a module without updating this decision
table fails immediately.
"""

MODULE_VIEW_COVERAGE: dict[str, tuple[str, ...]] = {
    "analysis._bigints": ("analysis.facts.bigint-ranges", "pass.ssa.bytemath_ranges"),
    "analysis._byte_lengths": ("analysis.facts.byte-lengths", "pass.ssa.byte_lengths"),
    "analysis._constants": ("analysis.facts.constants", "pass.ssa.constants"),
    "analysis._input_aliases": ("analysis.facts.constants", "pass.ssa.input_aliases"),
    "analysis._range_arithmetic": ("analysis.facts.ranges", "pass.ssa.range_arithmetic"),
    "analysis._range_refinement": ("repr.ssa.guarded", "pass.ssa.assert_ranges"),
    "analysis._range_seed": ("analysis.facts.ranges", "pass.ssa.range_seeds"),
    "analysis._scratch": ("analysis.scratch", "pass.ssa.scratch_constants",
                           "pass.ssa.scratch_values"),
    "analysis.auth": ("analysis.auth",),
    "analysis.context": ("repr.ssa.value", "repr.ssa.guarded",
                         "repr.ssa.presentation", "analysis.facts.constants"),
    "analysis.render": ("repr.ssa.presentation",),
    "ast.ast": ("repr.ast",),
    "ast.literals": ("repr.source", "repr.ast"),
    "ast.parse": ("repr.ast",),
    "budget.advanced": ("analysis.method_budget", "analysis.opcode_budget_guards",
                        "analysis.budget_exhaustion"),
    "budget.context": ("analysis.loop_bounds", "analysis.method_budget"),
    "budget.costs": ("analysis.block_costs",),
    "budget.loop_bounds": ("analysis.loop_bounds",),
    "budget.queries": ("analysis.method_budget",),
    "cfg.build": ("repr.ast", "repr.cfg"),
    "cfg.cfg": ("repr.cfg",),
    "cfg.dominance": ("analysis.dominance", "analysis.control_dependence"),
    "cfg.exits": ("analysis.path_predicates", "repr.structure"),
    "cfg.group": ("analysis.group",),
    "cfg.path_predicates": ("analysis.path_predicates",),
    "cfg.structure": ("repr.structure",),
    "cfg.subroutines": ("repr.structure", "analysis.callee_effects"),
    "cfg.super_auth": ("analysis.caller_guard_bypass",),
    "cfg.supercfg": ("repr.supercfg",),
    "dataflow.bounds": ("analysis.bounds",),
    "dataflow.box": ("analysis.box_flow",),
    "dataflow.byte_taint": ("analysis.byte_taint",),
    "dataflow.engine": ("analysis.taint",),
    "dataflow.group_taint_graph": ("analysis.group_taint",),
    "dataflow.predicate_aware": ("analysis.predicate_validation",),
    "dataflow.relational": ("analysis.relational_lengths",),
    "dataflow.state": ("analysis.state_flow",),
    "dataflow.taint_graph": ("analysis.taint",),
    "dataflow.taint_query": ("analysis.taint",),
    "dataflow.xcontract_taint_graph": ("analysis.xcontract_taint",),
    "diagnostics.health": ("analysis.health",),
    "frontend.graph": ("repr.ast",),
    "frontend.source_map": ("analysis.source_map",),
    "frontend.sources": ("repr.source",),
    "intercontract.analysis": ("analysis.xcontract_predicates",
                               "analysis.xcontract_auth", "repr.supercfg"),
    "language.constants": ("pass.ssa.constants",),
    "lift.arc4_recovery": ("analysis.abi",),
    "lift.backend": ("repr.puya_ir",),
    "lift.box_recovery": ("analysis.storage", "analysis.abi"),
    "lift.fund_flow": ("analysis.abi", "analysis.taint"),
    "lift.lift": ("repr.pre_ir",),
    "lift.pre_ir": ("repr.pre_ir",),
    "lift.summaries": ("analysis.callee_effects",),
    "lift.taint": ("analysis.taint", "analysis.byte_taint"),
    "lift.to_puya_ir": ("repr.puya_ir", "pass.lift.lower_to_puya",
                        "pass.lift.optimize_puya"),
    "lift.transforms": ("pass.lift.prune_dead_phis",
                        "pass.lift.isolate_cross_group_phis",
                        "pass.lift.tail_duplicate_mixed_joins"),
    "lift.type_recovery": ("pass.lift.recover_types", "pass.lift.finalize_types"),
    "metadata.abi": ("analysis.abi",),
    "metadata.arc56": ("analysis.abi", "analysis.storage"),
    "passes.range_assert": ("pass.ssa.assert_ranges",),
    "reporting.inner_transactions": ("analysis.inner_transactions",),
    "ssa.callee_effects": ("analysis.callee_effects",),
    "ssa.const_fold": ("pass.ssa.constants",),
    "ssa.frame_band": ("analysis.frame",),
    "ssa.frame_slots": ("analysis.frame",),
    "ssa.inner_txn_fields": ("analysis.inner_txn_fields",),
    "ssa.models": ("repr.ssa.canonical",),
    "ssa.operands": ("repr.ssa.canonical",),
    "ssa.presentation": ("pass.ssa.cleanup_unused_ssavars",),
    "ssa.producers": ("repr.ssa.canonical",),
    "ssa.program": ("repr.ssa.canonical",),
    "ssa.relations": ("analysis.frame", "analysis.scratch"),
    "ssa.render": ("repr.ssa.canonical",),
    "ssa.scratch_influence": ("analysis.scratch",),
    "ssa.ssa": ("repr.pyssa", "repr.ssa.canonical"),
    "ssa.stacksim": ("repr.pyssa", "analysis.frame", "analysis.callee_effects"),
    "ssa.value_rewrite": ("pass.ssa.stack_shuffles",),
}


NON_PRODUCT_MODULES: dict[str, str] = {
    "dataflow._nx_view": "shared graph query/copy primitives; no independent product",
    "diagnostics.errors": "typed exception definitions; no analysis result",
    "language.avm": "langspec metadata consumed by represented analyses",
    "lift.__main__": "command wrapper around repr.pre_ir/repr.puya_ir",
    "lift._puya_compat": "dependency compatibility checks reported as analysis health",
    "lift.cache": "revision/file-keyed cache plumbing; no independent product",
    "lift.teal_const": "literal conversion plumbing; no independent product",
    "reporting.registry": "detector registration plumbing; findings are outside tealtools views",
}


__all__ = ["MODULE_VIEW_COVERAGE", "NON_PRODUCT_MODULES"]
